"""Thumbnail storage backend (local disk in dev, Cloud Storage in production).

Slide thumbnails (PNG) are generated by the ingest pipeline and served by
``GET /api/thumbnails/files/{file_id}/{page_no}.png``. Where they live is
selected by :func:`config.use_gcs_thumbnails` (keyed off ``THUMBNAIL_BUCKET``):

* **local disk** (dev, default) — files under ``THUMB_ROOT`` (``data/thumbnails``).
  This is the historical behaviour; nothing changes locally.
* **Cloud Storage** (production) — objects at
  ``{prefix}/{safe_file_id}/{page_no}.png`` in the configured bucket, accessed
  via ADC (no key file). Cloud Run's local disk is ephemeral and per-instance,
  so persisting thumbnails in GCS lets them survive restarts and be shared
  across instances.

The ingest pipeline always renders to a local temp dir first (Gemini needs the
file on disk); :func:`put_file` then mirrors those PNGs to the active backend.
"""
from __future__ import annotations

import asyncio
import logging
import shutil
from pathlib import Path

import config

log = logging.getLogger("ingest.thumbnails")

# Local cache/root for rendered thumbnails (also the dev serving location).
THUMB_ROOT = Path(__file__).parent / "data" / "thumbnails"

_GCS_SCOPES = ["https://www.googleapis.com/auth/devstorage.read_write"]


def safe_name(file_id: str) -> str:
    return "".join(c for c in file_id if c.isalnum() or c in "-_")


def _blob_name(safe: str, page_no: int) -> str:
    return f"{config.thumbnail_prefix()}/{safe}/{page_no}.png"


# --- GCS client (lazy, cached) ---------------------------------------------

_bucket = None


def _gcs_bucket():
    """Return the configured GCS bucket handle, built once via ADC."""
    global _bucket
    if _bucket is None:
        from google.cloud import storage  # imported lazily; optional dep

        client = storage.Client(
            project=config.gcp_project(),
            credentials=config.adc_credentials(_GCS_SCOPES),
        )
        _bucket = client.bucket(config.thumbnail_bucket())
    return _bucket


# --- Sync workers (run via asyncio.to_thread) ------------------------------

def _gcs_upload_dir(safe: str, local_dir: Path) -> None:
    bucket = _gcs_bucket()
    for png in sorted(local_dir.glob("*.png")):
        page_no = png.stem
        blob = bucket.blob(f"{config.thumbnail_prefix()}/{safe}/{page_no}.png")
        blob.cache_control = "public, max-age=300"
        blob.upload_from_filename(str(png), content_type="image/png")


def _gcs_get(safe: str, page_no: int) -> bytes | None:
    blob = _gcs_bucket().blob(_blob_name(safe, page_no))
    if not blob.exists():
        return None
    return blob.download_as_bytes()


def _gcs_delete_prefix(safe: str) -> None:
    bucket = _gcs_bucket()
    prefix = f"{config.thumbnail_prefix()}/{safe}/"
    for blob in bucket.list_blobs(prefix=prefix):
        blob.delete()


# --- Public async API -------------------------------------------------------

async def clear_file(file_id: str) -> None:
    """Remove all thumbnails for a file (before re-ingest / on delete)."""
    safe = safe_name(file_id)
    local_dir = THUMB_ROOT / safe
    if local_dir.exists():
        shutil.rmtree(local_dir, ignore_errors=True)
    if config.use_gcs_thumbnails():
        try:
            await asyncio.to_thread(_gcs_delete_prefix, safe)
        except Exception:
            log.exception("failed clearing GCS thumbnails for %s", file_id)


async def put_file(file_id: str, local_dir: Path) -> None:
    """Publish the rendered PNGs in ``local_dir`` to the active backend.

    Local backend: PNGs already live under ``THUMB_ROOT`` — nothing to do.
    GCS backend: upload each page, then drop the local copies so Cloud Run's
    ephemeral disk doesn't fill up.
    """
    if not config.use_gcs_thumbnails():
        return
    safe = safe_name(file_id)
    await asyncio.to_thread(_gcs_upload_dir, safe, local_dir)
    shutil.rmtree(local_dir, ignore_errors=True)


async def get(file_id: str, page_no: int) -> bytes | None:
    """Return PNG bytes for a slide page, or ``None`` if absent."""
    safe = safe_name(file_id)
    if config.use_gcs_thumbnails():
        return await asyncio.to_thread(_gcs_get, safe, page_no)
    p = THUMB_ROOT / safe / f"{page_no}.png"
    if not p.exists():
        return None
    return await asyncio.to_thread(p.read_bytes)
